### ISSUE TITLE
No plugin found

### ISSUE THREAD

**Issue by jdlongenecker** [actions-on-google/smart-home-dashboard#10]
Hello!

I'm trying to get this working on my Mac and have successfully completed the client setup and am almost done with the server setup--but when I get to the deploy command (mvn appengine:deploy), I get an error "No plugin found for prefix 'appengine' in the current project and in the plugin groups". Do you have any advice on how to fix this? I've tried searching around but haven't made any progress yet. 

Thanks!

**Comment by Aymkdn** [comment]
Thanks, it gave me a tip to find the resolution.

After trying several different folders, I found it must be ran from the top folder: `smart-home-dashboard/`
