### ISSUE TITLE
What's the agent user Id?

### ISSUE THREAD

**Issue by Sharvin26** [actions-on-google/smart-home-dashboard#11]
<img width="1024" alt="smart home dashboard" src="https://user-images.githubusercontent.com/17084209/49568217-5bf3ad00-f956-11e8-913a-b22cc08ee229.png">
I am confused what's the agent user id here?

**Comment by Fleker** [comment]
It's the agent user ID of your service. From [the docs](https://developers.google.com/actions/smarthome/create#actiondevicessync):

> agentUserId: String (up to 256 bytes). Required. Reﬂects the unique (and immutable) user ID on the agent's platform. The string is opaque to Google, so if there's an immutable form vs a mutable form on the agent side, use the immutable form (e.g. an account number rather than email).

**Comment by Sharvin26** [comment]
Yes in my case I am using login with Amazon so what would be the agent user id?

**Comment by Fleker** [comment]
There's no API for virtual devices. If you want to add simulated devices, you could use this sample for instance or you'd need to return a list of virtual devices in your SYNC response.

**Comment by Sharvin26** [comment]
Yes, I am Wondering how to use this to add simulated devices in this sample?

**Comment by Fleker** [comment]
You don't add anything to your Request Sync or Report State. In your `SYNC`, you are supposed to return all the devices for your user.

**Comment by Sharvin26** [comment]
Suppose user adds new devices in that case the Manufacturer cloud needs to report Homegraph about the new device added according to my understanding. So, in that case, I need to use Request Sync. So in this Python Script:
```
import requests
api_key = '' // Added the API key from Homegraph
agent_user_id = '' // Tried all 3 above values (name, email and UserId )
def request_sync():
    url = 'https://homegraph.googleapis.com/v1/devices:requestSync?key=' + api_key
    data = {"agentUserId": agent_user_id};
    response = requests.post(url, json=data)
    print 'Response:' + response.text
    print 'Response Status code:' + str(response.status_code)
request_sync()
```
Where do I pass the new device list in the post request to homegraph?

**Comment by Fleker** [comment]
The `agent_user_id` should be the same identifier you return in the original SYNC. Otherwise, you're trying to request a SYNC for a user that does not exist, which is a 404.

**Comment by Sharvin26** [comment]
The `agent_user_id` is same in the Sync Intent and Report State post call. It's working fine for this smart home dashboard demo but not working for above Script. 
Even I tried the Script given in [documentation](https://developers.google.com/actions/smarthome/report-state):
```
"""A tool for calling HomeGraph API with a JWT signed by a Google API Service Account."""

import argparse
import time
import json
import io

import google.auth.crypt
import google.auth.jwt
import requests
from six.moves import urllib

def generate_jwt(service_account_file):
    """Generates a signed JSON Web Token using a Google API Service Account."""

    # Note: this sample shows how to manually create the JWT for the purposes
    # of showing how the authentication works, but you can use
    # google.auth.jwt.Credentials to automatically create the JWT.
    #   http://google-auth.readthedocs.io/en/latest/reference
    #   /google.auth.jwt.html#google.auth.jwt.Credentials

    signer = google.auth.crypt.RSASigner.from_service_account_file(
        service_account_file)

    now = int(time.time())
    expires = now + 3600  # One hour in seconds

    iss = ''

    with io.open(service_account_file, 'r', encoding='utf-8') as json_file:
        data = json.load(json_file)
        iss = data['client_email']

    payload = {
        'iat': now,
        'exp': expires,
        'aud': 'https://accounts.google.com/o/oauth2/token',
        'iss': iss,
        'scope': 'https://www.googleapis.com/auth/homegraph'
    }

    signed_jwt = google.auth.jwt.encode(signer, payload)

    return signed_jwt


def get_access_token(signed_jwt):
    url = 'https://accounts.google.com/o/oauth2/token'
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    data = 'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=' + signed_jwt

    response = requests.post(url, headers=headers, data=data)

    if response.status_code == requests.codes.ok:
        token_data = json.loads(response.text)
        return token_data['access_token']

    response.raise_for_status()
    return 'ERROR'

def report_state(access_token, report_state_file):
    url = 'https://homegraph.googleapis.com/v1/devices:reportStateAndNotification'
    headers = {
        'X-GFE-SSL': 'yes',
        'Authorization': 'Bearer ' + access_token
    }
    data = {}

    with io.open(report_state_file, 'r', encoding='utf-8') as json_file:
        data = json.load(json_file)

    response = requests.post(url, headers=headers, json=data)

    print 'Response: ' + response.text

    return response.status_code == requests.codes.ok

def main(service_account_file, report_state_file):
    signed_jwt = generate_jwt(service_account_file)
    print('signed JWT: ' + signed_jwt)

    access_token = get_access_token(signed_jwt)
    print('access token: ' + access_token)

    success = report_state(access_token, report_state_file)
    if success:
        print 'Report State has been done successfully.'
    else:
        print 'Report State failed. Please check the log above.'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        'service_account_file',
        help='The path to your service account json file.')
    parser.add_argument(
        'report_state_file',
        help='The path to the json file containing the states you want to report.')

    args = parser.parse_args()

    main(args.service_account_file, args.report_state_file)
```
Error:
```
Response: {
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}

Report State failed. Please check the log above.
```

**Comment by Fleker** [comment]
Okay, I see. Do the devices you're reporting already exist for that user?

**Comment by Sharvin26** [comment]
Yes, Devices do Exists for the user. I have a total of 10 appliances for that user and I am sending a state for appliance-1 using Report State.

**Comment by Sharvin26** [comment]
Yes, I see all the appliances on the dashboard list for this smart home dashboard project.

**Comment by Sharvin26** [comment]
Yes, I see all the devices for that agentUserId and deviceID for this smart home dashboard project:-

![smarthome dashboard](https://user-images.githubusercontent.com/17084209/49991206-5e818280-ffa6-11e8-9a46-0a2f0fc0dee0.png)

**Comment by Sharvin26** [comment]
@eric30 I tried the above scenario. The new state was not taken. But in the gcloud console logs for this smart home dashboard project, I got the following:-

~ "POST /upload HTTP/1.1" 200
~ "GET /homegraph?agentUserId=myagentUserId&file=file.json HTTP/1.1" 200
~  "GET /refresh?agentUserId=myagentUserId HTTP/1.1" 200
~ "GET /refresh?agentUserId=myagentUserId HTTP/1.1" 200

**Comment by Sharvin26** [comment]
Thank you, sir, It Started working for all the Appliances I am not Sure how but It started working properly.

**Comment by prangdal** [comment]
I have a question with regards to the google report state, since this is a proactive call to google to push the device state we would need the json key file of the service account. In case i have multiple projects under google console based on brand, environment and each of them has different keys, how do it know for an appliance which service key is to be used for pushing the device state via report state. ?

**Comment by Fleker** [comment]
It uses the keys to generate a unique token that is associated with a project id. If the token is not generated correctly, or it's a bad token, the request will be denied.

**Comment by malikasinger1** [comment]
> The `agent_user_id` should be the same identifier you return in the original SYNC. Otherwise, you're trying to request a SYNC for a user that does not exist, which is a 404.

@Fleker your response really helped me out, this is something you must need to mention in the document
