### ISSUE TITLE
Can't run standalone

### ISSUE THREAD

**Issue by khenderick** [actions-on-google/smart-home-dashboard#18]
I could not run it locally. However, I managed to fix it by:

1. Remove the tomcat exclusion in the `pom.xml` for `spring-boot-starter-web`.
2. Build with the command `mvn clean package spring-boot:repackage`

Not sure whether that would have any impact on e.g. running it on the app engine.

**Comment by paulschuetz** [comment]
please fix the readme!

**Comment by Fleker** [comment]
I'm checking this out now.

**Comment by Fleker** [comment]
Seems like the changes suggested here do not prevent the App Engine deployment.
