### ISSUE TITLE
BUILD FAILURE - cannot find symbol (symbol:   class Generated, location: package javax.annotation)

### ISSUE THREAD

**Issue by ldgmaia** [actions-on-google/smart-home-dashboard#19]
When executing "mvn appengine:deploy" I'm getting the following error:

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/lmaia/Desktop/smart-home-dashboard/src/main/java/com/google/home/graph/v1/HomeGraphApiServiceGrpc.java:[26,18] cannot find symbol
  symbol:   class Generated
  location: package javax.annotation
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.731 s
[INFO] Finished at: 2019-03-06T09:27:58-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project dashboard: Compilation failure
[ERROR] /C:/Users/XXX/Desktop/smart-home-dashboard/src/main/java/com/google/home/graph/v1/HomeGraphApiServiceGrpc.java:[26,18] cannot find symbol
[ERROR]   symbol:   class Generated
[ERROR]   location: package javax.annotation
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Even executing with -X or -e flags did not help at all.

What could be causing this error?

**Comment by Fleker** [comment]
I'm not sure.

**Comment by surjitr** [comment]
I had the same issue on Ubuntu 18. I tried the same on Ubuntu 16.04 and worked without any issues. Just FYI in case if it helps.

**Comment by chearmstrong** [comment]
Same issue on MacOS 10.14 for me.

**Comment by ldgmaia** [comment]
I tried with Git Bash and it worked!

**Comment by sfranchois** [comment]
Ran into the exact same issue today. MacOS 10.14.
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
javac 11.0.2

**Comment by Fleker** [comment]
I can't reproduce this error.

**Comment by edwardtoday** [comment]
Same issue.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project dashboard: Compilation failure
[ERROR] /Users/qingpei/Downloads/smart-home-dashboard/src/main/java/com/google/home/graph/v1/HomeGraphApiServiceGrpc.java:[26,18] cannot find symbol
[ERROR]   symbol:   class Generated
[ERROR]   location: package javax.annotation
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

macOS 10.14.4 (18E226)

```
$ java --version
java 11 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

$ javac --version
javac 11

$ uname -a
Darwin Q-MBP13.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64 i386 MacBookPro14,2 Darwin
```

**Comment by daveyostcom** [comment]
Nobody here is getting any work done? Anybody have a workaround?

**Comment by TBM5K** [comment]
Also ran into the same problem on windows

**Comment by daveyostcom** [comment]
This is the fix:

```
  <dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifact Id>
    <version>1.2</version>
  </dependency>
```

**Comment by bilsak18** [comment]
@daveyostcom Where does this code must go ?

**Comment by bilsak18** [comment]
> This is the fix:
> 
> ```
>   <dependency>
>     <groupId>javax.annotation</groupId>
>     <artifactId>javax.annotation-api</artifact Id>
>     <version>1.2</version>
>   </dependency>
> ```

@daveyostcom Where does this code must go ?

**Comment by daveyostcom** [comment]
pom.xml file

**Comment by kaungmyatpaing21** [comment]
> > This is the fix:
> > ```
> >   <dependency>
> >     <groupId>javax.annotation</groupId>
> >     <artifactId>javax.annotation-api</artifact Id>
> >     <version>1.2</version>
> >   </dependency>
> > ```
> 
> @daveyostcom Where does this code must go ?

It's worked for me!

**Comment by munakaghamelu** [comment]
It didn't work for me, I am having problems with antlr are there any other fixes please?

**Comment by thundervolt10** [comment]
I can't fix with this method
Do you have any other method for this issue?

**Comment by BotMichael** [comment]
> This is the fix:
> 
> ```
>   <dependency>
>     <groupId>javax.annotation</groupId>
>     <artifactId>javax.annotation-api</artifact Id>
>     <version>1.2</version>
>   </dependency>
> ```

Also worked for me. Thank you so much!!!

**Comment by ethanrucinski** [comment]
This fix works but for folks who are not familiar with XML you will need to use it without syntax errors:

`<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.2</version>
  </dependency>`


Simply place this within the <dependancies> tags of your pom.xml file and the build should work fine.

**Comment by bradleyewong** [comment]
Except remove the space from the closing <artifactId>  tag:

```
  <dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.2</version>
  </dependency>
```

you put this in the <dependencies> node of :
/core/pom.xml

**Comment by Prasad-vangapandu** [comment]
unable to save the file.. it showing permission denied

**Comment by virenderkamboj7** [comment]
I am still not able to resolve this
Tried::
<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>1.2</version>
		</dependency>

But still getting same issue::
[ERROR] /C:/Users/orange/eclipse-workspace/PVRAPIs/src/test/java/TestCases/TC_Test_008.java:[205,33] cannot find symbol                                                     [ERROR]   symbol:   class Rootseatresearve 

Can anybody help ?

**Comment by Arth-Arsh-cloud** [comment]
Please add this dependency also in your pom.xml and it will surely work. It worked for me. 

<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.2</version>
  </dependency>

**Comment by kevin-antony-software** [comment]
> <dependency>
>     <groupId>javax.annotation</groupId>
>     <artifactId>javax.annotation-api</artifact Id>
>     <version>1.2</version>
>   </dependency>

Its worked for me too. Thanks

**Comment by SumuduSampath** [comment]
I added javaX annotation. but still getting error.

**Comment by kuchaguangjie** [comment]
There is a new version for `javax.annotation-api`:
```
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.3.2</version>
    </dependency>
```
