### ISSUE TITLE
error TS2339: Property 'subscribe' does not exist on type '"" | Observable<any>'.

### ISSUE THREAD

**Issue by rahulchincholikar** [actions-on-google/smart-home-dashboard#2]
after executing 
$ npm run build 
throwing this error 

ERROR in src/app/device-list/device-list.component.ts(51,48): error TS2339: Property 'subscribe' does not exist on type '"" | Observable<any>'.
  Property 'subscribe' does not exist on type '""'.
src/app/device-list/device-list.component.ts(72,46): error TS2339: Property 'subscribe' does not exist on type '"" | Observable<any>'.
  Property 'subscribe' does not exist on type '""'

**Comment by Fleker** [comment]
Yeah it seems to be a general TypeScript issue as the type is `Observable | string` instead of just `Observable`. I'll work on a fix.

```
get(searchTerm) {
    const apiLink = this.giphyApi + searchTerm;
    return this.http.get(apiLink).map((response: any) => {
      if (this.apiKey === 'api-key') {
        // Use undefined image
        return '';
      }

      if (response.data.length > 0) {
        return response.data[0].images.original.url;
      } else {
        return 'https://media.giphy.com/media/YaOxRsmrv9IeA/giphy.gif'; // dancing cat for 404
      }
    });
  }
```

**Comment by rahulchincholikar** [comment]
thank you bentech and fleker for help

**Comment by Fleker** [comment]
This has been resolved
