### ISSUE TITLE
How to run in tomcat

### ISSUE THREAD

**Issue by shenhuaxiyuan** [actions-on-google/smart-home-dashboard#20]
I build with command "mvn clean package"   and get a war file named "dashboard-0.1.0-SNAPSHOT.war" , then deployed in tomcat successfully. But when I go to url "http://localhost:8080/dashboard-0.1.0-SNAPSHOT" in my browser , there is an empty page here !

**Comment by surjitr** [comment]
Facing the same issue. Getting an empty page. 	shenhuaxiyuan  were you able to get through? any workaround.

**Comment by mikevlz** [comment]
Tomcat extracts WAR-file. I've copied the extracted structure to the ROOT directory, after that TOMCAT opens it and serves. There some glitches with 404 error, or page refresh.

**Comment by dmcamens-legrand** [comment]
@Fleker Hi I had the same issue (blank page).  I did what @mikevlz suggested (delete the contents of ROOT and replace with the contents of the dashboard-0.1.0-SNAPSHOT folder) and it worked, but I don't think that is a very good permanent solution.  Is there some issue with the web app or is it a Tomcat issue or what?  It would be nice to have steps in the readme file that cover this case.  Thanks!

**Comment by Fleker** [comment]
I'm unfamiliar with Tomcat, just with the local/app engine setups.
