### ISSUE TITLE
How to deploy it to Server ? Getting " no main manifest attribute" error while running war/jar

### ISSUE THREAD

**Issue by varadujjainkar** [actions-on-google/smart-home-dashboard#24]

**Comment by Fleker** [comment]
Are you building on Windows?

**Comment by varadujjainkar** [comment]
Yes!! now I am facing totally different issue, its showing the devices but not showing the traits I cross checked for different devices and for different skill as well. PFB the link it is happing many times even though the sync is working and state report rest call is success.
[https://drive.google.com/open?id=1iDX1Nd6AljwLxDDWmH4jkla4E-P52bIh](url)

**Comment by Fleker** [comment]
If that's happening, there may be an issue with your report state implementation, as something would then be shown in the homegraph.

**Comment by varadujjainkar** [comment]
It's an intermediate issue, Sometimes it shows traits but sometimes it didn't and I can see the response log for report state is a success in both the cases.

**Comment by Fleker** [comment]
If you check network logs, can you see if it's related to the sample if the actual responses are correct?

**Comment by varadujjainkar** [comment]
Yes! They are correct !! and cross checked on different devices ans open network also!

**Comment by Fleker** [comment]
Okay, if it's a sample bug that at least is reassuring for you. Then it comes down to where in the sample code the issue is coming up?
