### ISSUE TITLE
Dashboard fields

### ISSUE THREAD

**Issue by symdeb** [actions-on-google/smart-home-dashboard#27]
The documentation says:

On the dashboard, do the following:

    Choose your Account Key File
    Add your Access Token
    Add your Fulfillment URL
    Add your agentUserID

My dashboard does not show the Fulfillment URL and Access token. As follows:
![image](https://user-images.githubusercontent.com/19564066/63311352-60b79000-c330-11e9-89f7-bfa604f11997.png)

**Comment by symdeb** [comment]
https://developers.google.com/actions/smarthome/develop/report-state
in section"Deploy the Report State dashboard"

**Comment by Fleker** [comment]
I've filed an issue to fix the doc.

**Comment by symdeb** [comment]
Thanks a lot !

**Comment by Fleker** [comment]
Doc change was submitted.
