### ISSUE TITLE
device-list.component.html does not compile

### ISSUE THREAD

**Issue by avernonquantify** [actions-on-google/smart-home-dashboard#28]
npm run build fails and can be easily fixed by updating the src/app/device-list/device-list.component.html file
Replace
``` html
<img mat-list-avatar ng-show="{{device.giphyUrl}}" src="{{device.giphyUrl}}" alt="{{device.name}}">
<i mat-list-avatar class="material-icons md-48 md-light" ng-show="{{!device.giphyUrl}}">{{device.icon}}</i>

```
with

``` html
<img mat-list-avatar [hidden]="!device.giphyUrl" src="{{device.giphyUrl}}" alt="{{device.name}}">
<i mat-list-avatar class="material-icons md-48 md-light" [hidden]="device.giphyUrl">{{device.icon}}</i>
```

**Comment by Fleker** [comment]
Why is it not compiling? That syntax was working when I ran a build.

**Comment by avernonquantify** [comment]
ArthursMacBookPro:ngapp arthurvernon$ npm run build

> client@0.0.0 build /Users/arthurvernon/https/smart-home-dashboard/src/main/ngapp
> ng build --prod && cp -r ../appengine/* ../webapp/

Date: 2019-09-18T04:31:04.057Z                                                     
Hash: f79b39e48d050f471bdd
Time: 4474ms
chunk {0} styles.8a126321729b8c0aa334.bundle.css (styles) 46.9 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in : Can't bind to 'ng-show' since it isn't a known property of 'img'. ("gStyle]="{'background-color':device.updated ? 'green' : '#424242' }">

        <img mat-list-avatar [ERROR ->]ng-show="{{device.giphyUrl}}" src="{{device.giphyUrl}}" alt="{{device.name}}">
        <i mat-list-av")
: Can't bind to 'ng-show' since it isn't a known property of 'i'. ("giphyUrl}}" alt="{{device.name}}">
        <i mat-list-avatar class="material-icons md-48 md-light" [ERROR ->]ng-show="{{!device.giphyUrl}}">{{device.icon}}</i>
        <h3 mat-line class='device-name'>{{device.")

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.0.0 build: `ng build --prod && cp -r ../appengine/* ../webapp/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arthurvernon/.npm/_logs/2019-09-18T04_31_04_091Z-debug.log

**Comment by avernonquantify** [comment]
If my understanding is correct, ng-show is angular 1.

**Comment by Fleker** [comment]
Okay I'll get a bug fix started.

**Comment by Fleker** [comment]
Seems like it works without the curly brackets, ie. `ng-show="device.giphyUrl"`. Is there an advantage to using `hidden`?

**Comment by raju102** [comment]
<img mat-list-avatar *ngIf="device.giphyUrl" src="{{device.giphyUrl}}" alt="{{device.name}}">
        <i mat-list-avatar class="material-icons md-48 md-light" *ngIf="!device.giphyUrl">{{device.icon}}</i>
        <h3 mat-line class='device-name'>{{device.name}} ({{device.nicknames.join(',')}}) ({{device.id}})</h3>

**Comment by avernonquantify** [comment]
hidden is standard html 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
