### ISSUE TITLE
while running my maven project Im can not find a symbol error .... give me a suggest to resolve    this problem

### ISSUE THREAD

**Issue by natrajan0409** [actions-on-google/smart-home-dashboard#29]
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.organization.name:Maveen:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.seleniumhq.selenium:selenium-java:jar -> version 2.53.0 vs 4.0.0-alpha-2 @ line 136, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] --------------------< com.organization.name:Maveen >--------------------
[INFO] Building Maveen 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Maveen ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Maveen ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 33 source files to E:\ECLIPS\WORKSPACE1\Maveen-B2000\Maveen\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/version/TEST.java:[12,52] package com.sun.xml.internal.ws.wsdl.writer.document does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[10,18] package org.testng does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[11,30] package org.testng.annotations does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[12,30] package org.testng.annotations does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[13,30] package org.testng.annotations does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[3,30] package org.testng.annotations does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[22,2] cannot find symbol
  symbol:   class Test
  location: class pom.login
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[51,2] cannot find symbol
  symbol:   class DataProvider
  location: class pom.login
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[7,4] cannot find symbol
  symbol:   class Test
  location: class jave.loginTest
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[12,4] cannot find symbol
  symbol:   class Test
  location: class jave.loginTest
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[17,4] cannot find symbol
  symbol:   class Test
  location: class jave.loginTest
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[22,4] cannot find symbol
  symbol:   class Test
  location: class jave.loginTest
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[43,17] cannot find symbol
  symbol:   variable Assert
  location: class pom.login
[INFO] 13 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.053 s
[INFO] Finished at: 2019-09-26T08:18:03+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Maveen: Compilation failure: Compilation failure: 
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/version/TEST.java:[12,52] package com.sun.xml.internal.ws.wsdl.writer.document does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[10,18] package org.testng does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[11,30] package org.testng.annotations does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[12,30] package org.testng.annotations does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[13,30] package org.testng.annotations does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[3,30] package org.testng.annotations does not exist
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[22,2] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class pom.login
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[51,2] cannot find symbol
[ERROR]   symbol:   class DataProvider
[ERROR]   location: class pom.login
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[7,4] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class jave.loginTest
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[12,4] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class jave.loginTest
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[17,4] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class jave.loginTest
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/jave/loginTest.java:[22,4] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class jave.loginTest
[ERROR] /E:/ECLIPS/WORKSPACE1/Maveen-B2000/Maveen/src/main/java/pom/login.java:[43,17] cannot find symbol
[ERROR]   symbol:   variable Assert
[ERROR]   location: class pom.login
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Fleker** [comment]
Based on your stacktrace, it looks like this is for a project called Maveen and has several typos (jave instead of java). Is this the smart-home-dashboard project?

**Comment by proppy** [comment]
Closing as obsolete.
