### ISSUE TITLE
Device List Not shown for the agentuserId:

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-dashboard#34]
Hi ,
I have followed the steps to deploy the smart home dashboard.
I have uploaded my jwt-key and agentUserId. But i am not able to see the device list for the user.
This is on Windows 10 machine.
![Capture](https://user-images.githubusercontent.com/31435615/71169179-583f7980-227e-11ea-97cb-7e998c499a6c.PNG)

**Comment by Fleker** [comment]
Can you see any errors in your server?

**Comment by sakthisg** [comment]
No errors found.
Please find the zip file containing deployment logs and accessing the appspot logs.

[Logs.zip](https://github.com/actions-on-google/smart-home-dashboard/files/3986714/Logs.zip)

**Comment by sakthisg** [comment]
@Fleker : Any clue on this issue?

**Comment by Fleker** [comment]
If there's no errors found, then it's hard to provide a response.

**Comment by sakthisg** [comment]
I was able to run in Windows 7 and found to be working last year. After
Windows 10.Do you know is there anything specific to Windows 10 to be done
for setting it up?

**Comment by Fleker** [comment]
Are you deploying it to App Engine? It shouldn't matter which OS you're using.

**Comment by sakthisg** [comment]
Yes. I have followed the instructions given in the Google link

**Comment by Fleker** [comment]
I don't see any issues.
