### ISSUE TITLE
State of the device is coming empty

### ISSUE THREAD

**Issue by varadujjainkar** [actions-on-google/smart-home-dashboard#35]
After latest changes, we are not able to see the state of the device it showing as empty although response is coming as expected i.e., we can the response json in the tab in the below the devices list

Cross checked below,

Sync: Working as expected.
Report State: Working as expected getting 200 response code.

**Comment by Fleker** [comment]
Do you see the data in the Network tab of the web developer tools?

**Comment by varadujjainkar** [comment]
PFA,

Screenshot of Network Tab of the web developer tools.

![image](https://user-images.githubusercontent.com/22313829/73938930-52752480-490e-11ea-8390-adbfab322c7f.png)

Screenshot of Console Tab of the web developer tools.

![image](https://user-images.githubusercontent.com/22313829/73939516-a6343d80-490f-11ea-955a-d293e3a7fd90.png)

**Comment by Fleker** [comment]
Are you correctly reporting the device state to the Home Graph?

**Comment by varadujjainkar** [comment]
Yes! we are receiving 200 OK from the home graph api.

**Comment by varadujjainkar** [comment]
To Cross check report state, I tried to run Smart home Test Suite and it is also working as expected, but still I am not able to see data on Dashboard.

**Comment by Fleker** [comment]
Do you see any logs in the serverside code that would correspond to a bug or error happening before you get the results?

**Comment by elupus** [comment]
My guess is that it's the following code. If there is nothing in cache, it will never be added.
```
			for (Map.Entry<String, Object> state : deviceStates.entrySet()) {
				if (device.getStatesCache().containsKey(state.getKey()) &&
						!device.getStatesCache().get(state.getKey()).equals(state.getValue())) {
					// This state has changed!
					device.setUpdated(true);
					delta.append(state).append(" | ");
					device.getStatesCache().put(state.getKey(), state.getValue());
				}
			}
```

**Comment by Fleker** [comment]
The cache should be prepopulated with data when the [SYNC occurs](https://github.com/actions-on-google/smart-home-dashboard/blob/master/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java#L119).

**Comment by elupus** [comment]
Devicelist yes. But the states for the device is empty at that point. Nothing can them every fill it. Since a state must be preexisting for it to be updated or added. (old code always did the put() call independent of the check for preexisting value.

**Comment by Fleker** [comment]
I can reproduce this on a clean build at HEAD. I suppose I should update the behavior to always set the cache.

**Comment by elupus** [comment]
Fix:

```diff
diff --git a/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java b/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java
index 804e3db..bb057cd 100644
--- a/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java
+++ b/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java
@@ -167,8 +169,8 @@ public class HomeGraphController implements Serializable {
 					// This state has changed!
 					device.setUpdated(true);
 					delta.append(state).append(" | ");
-					device.getStatesCache().put(state.getKey(), state.getValue());
 				}
+				device.getStatesCache().put(state.getKey(), state.getValue());
 			}
 		}
 		response.setDebugDelta(delta.toString());
```

**Comment by elupus** [comment]
Something more awray than just above fix. Delta becomes: "com.google.api.client.util.ArrayMap$Entry@910 | " which is rather unusable.

**Comment by elupus** [comment]
The whole flatten step that existed before has been removed.

**Comment by Fleker** [comment]
There were a number of changes that were made as part of a larger refactoring.

**Comment by Fleker** [comment]
I think I need to split the delta string building to explicitly append both the key and value. Working on it now.

**Comment by Fleker** [comment]
Adjusted the **Delta**, although I notice states still don't appear in the device list like they used to.

![image](https://user-images.githubusercontent.com/3291635/76242769-9a3ce380-620d-11ea-9a1a-ad53ecad224a.png)
