### ISSUE TITLE
Missing nickname in state crashes GUI

### ISSUE THREAD

**Issue by elupus** [actions-on-google/smart-home-dashboard#37]
If nicknames fields have not been set in data, the GUI crashes since the getNicknames() function will then return null.

I have worked around it like the following:

```diff
diff --git a/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java b/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java
index 804e3db..bb057cd 100644
--- a/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java
+++ b/src/main/java/com/google/homegraph/dashboard/controller/HomeGraphController.java
@@ -113,7 +113,9 @@ public class HomeGraphController implements Serializable {
 			device.setId(d.getId());
 			device.setType(d.getType().substring(d.getType().lastIndexOf('.') + 1));
 			device.setName(d.getName().getName());
-			device.setNicknames(d.getName().getNicknames());
+			if (d.getName().getNicknames() != null) {
+				device.setNicknames(d.getName().getNicknames());
+			}
 			deviceList.add(device);
 		}
 		deviceCache.put(agentUserId, deviceList);
```

Its unclear from docs if its allowable to be missing nicknames field. Its mentioned as optional.

**Comment by Fleker** [comment]
All of my tests have included the nickname, so it seems to be a bug and a null setter should be used. Feel free to file a PR with your patch, or I can do it later on.

**Comment by elupus** [comment]
could you check if it is allowable to be missing these fields?  https://developers.google.com/assistant/smarthome/reference/rest/v1/devices/sync#DeviceNames say you can optionally provide them, but doesn't really make a difference between nicknames/defaultNames field missing and it being an empty list.

HomeAssistant which i think is going through validation at the moment is not providing the fields.

**Comment by Fleker** [comment]
I do not believe the fields are required. If they SYNC correctly, then this project should reflect that.

**Comment by elupus** [comment]
Yea it seem to sync correctly. But i've never gotten reportstate updates to directly update GUI on any display nor in the android home app. I'm sort of going on straws at the moment :)

**Comment by Fleker** [comment]
The app/smart display have their own reasons for not adopting the states directly, but as long as you're reporting the state that's all you can do.
