### ISSUE TITLE
agent user id

### ISSUE THREAD

**Issue by arthurross88** [actions-on-google/smart-home-dashboard#41]
Hi,
Does anyone knoe how to retrieve my agenty user id?
Thank you in advance

**Comment by Fleker** [comment]
The agent user id comes from your [SYNC response](https://developers.google.com/assistant/smarthome/reference/intent/sync):

> Reﬂects the unique (and immutable) user ID on the agent's platform. The string is opaque to Google, so if there's an immutable form vs a mutable form on the agent side, use the immutable form (e.g. an account number rather than email).

**Comment by proppy** [comment]
Closing as obsolete.
