### ISSUE TITLE
Could I list 3rd party devices using smart-home-dashboard ?

### ISSUE THREAD

**Issue by AllenWu0913** [actions-on-google/smart-home-dashboard#46]
My google home app has linked Yeelight and Smart Plug(Smart life) devices, could I list all of devices(Home Graph) in my google account using SYNC ?  
Thanks~

**Comment by Fleker** [comment]
No, the platform does not provide a way for one to get devices nor states across all connected services, just the one for the service you create as a developer.

**Comment by AllenWu0913** [comment]
Hi Fleker, got it thanks~
