### ISSUE TITLE
COMPILATION ERROR - package org.testng.annotations does not exist 

### ISSUE THREAD

**Issue by vishal-camplus** [actions-on-google/smart-home-dashboard#47]
While trying to execute build in Jenkins I'm getting following error : 
- [ ] COMPILATION ERROR - package org.testng.annotations does not exist 
- [ ] cannot find symbol
  symbol:   class Test

Error : 

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JIS_Admin.java:[2,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JBIMS.java:[2,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/A2ADemo.java:[6,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/A2ADemo_Admin.java:[2,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JIS.java:[6,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JBIMS_Admin.java:[2,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JIS_Admin.java:[11,10] cannot find symbol
  symbol:   class Test
  location: class AdmissionToAlumni.JIS_Admin
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JBIMS.java:[11,10] cannot find symbol
  symbol:   class Test
  location: class AdmissionToAlumni.JBIMS
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/A2ADemo.java:[11,10] cannot find symbol
  symbol:   class Test
  location: class AdmissionToAlumni.A2ADemo
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/A2ADemo_Admin.java:[11,10] cannot find symbol
  symbol:   class Test
  location: class AdmissionToAlumni.A2ADemo_Admin
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JIS.java:[11,10] cannot find symbol
  symbol:   class Test
  location: class AdmissionToAlumni.JIS
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JBIMS_Admin.java:[11,10] cannot find symbol
  symbol:   class Test
  location: class AdmissionToAlumni.JBIMS_Admin
[INFO] 12 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.548 s
[INFO] Finished at: 2021-06-30T12:52:52+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project A2A_Scripts: Compilation failure: Compilation failure: 
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JIS_Admin.java:[2,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JBIMS.java:[2,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/A2ADemo.java:[6,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/A2ADemo_Admin.java:[2,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JIS.java:[6,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JBIMS_Admin.java:[2,30] package org.testng.annotations does not exist
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JIS_Admin.java:[11,10] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class AdmissionToAlumni.JIS_Admin
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JBIMS.java:[11,10] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class AdmissionToAlumni.JBIMS
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/A2ADemo.java:[11,10] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class AdmissionToAlumni.A2ADemo
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/A2ADemo_Admin.java:[11,10] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class AdmissionToAlumni.A2ADemo_Admin
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JIS.java:[11,10] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class AdmissionToAlumni.JIS
[ERROR] /C:/Users/Admin/.jenkins/A2A_Scripts/src/main/java/AdmissionToAlumni/JBIMS_Admin.java:[11,10] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class AdmissionToAlumni.JBIMS_Admin
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by Fleker** [comment]
It looks like your project is not the same as the **smart-home-dashboard** so I don't think this is the right place to file an issue. However, it does seem like there's an import error at `org.testng.annotations` which should instead be **testing**.
