### ISSUE TITLE
different ports

### ISSUE THREAD

**Issue by charinduedirisuriya** [actions-on-google/smart-home-dashboard#5]
If i build the front end with npm i get a web ui. But when i upload my json file i get 404 upload not found because the backend is running on my Apache server port(8080) and nodejs is using port 4200.

404 not found  localhost:4200/upload?filename=someone.json

How can fix this issue?

**Comment by Fleker** [comment]
If you build the backend and serve it, it should also be serving the frontend.

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
